title: Zhip

description: Zhip is the worlds first Zilliqa iOS wallet
url: ""

markdown: kramdown
theme: minima
exclude: [vendor]

markdown: kramdown
theme: minima

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

header_pages:
  - index.md
  - privacy.md